apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-uvbxxtgj
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-uvbxxtgj:eb5355a354d4a73b3a43a4816e0d281ea10bd101@sha256:ea340415b80cab55c93a03681f6cd9af46f27cb89f7355fc91584711d1c0eea4
          name: container-image
